services:
  server:
    container_name: fast_api_server
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: "./container/Dockerfile"
    env_file: .env
    environment: 
      GRANT_SUDO: "yes"
    volumes:
      - "./container/server:/code/app"
